name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch: # allow manual trigger

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate
    steps:
      - uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "profile-summary-cards"
